# Generated by Django 3.0.8 on 2021-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('product_code', models.CharField(max_length=150)),
                ('distributor_code', models.CharField(max_length=150)),
                ('dsr_code', models.CharField(max_length=150)),
                ('retailer_code', models.CharField(max_length=150)),
                ('activation_date', models.DateField()),
                ('lifting_date', models.DateField()),
                ('qcpass_date', models.DateField()),
                ('usage_date', models.DateField()),
                ('usage_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_3g_usage_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_4g_usage_value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
