# Generated by Django 3.0.8 on 2021-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210915_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activenumber',
            name='activation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='distributor_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='dsr_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='lifting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='net_3g_usage_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='net_4g_usage_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='product_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='qcpass_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='region',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='retailer_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='usage_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activenumber',
            name='usage_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
