# Generated by Django 3.0.8 on 2021-09-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
